/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  href?: string;
  icon?: string;
  isExternal?: boolean;
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  siteKeywords?: Array<string>;
  siteLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  ctaText?: string;
  ctaUrl?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  heroBackground?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  showBlog?: boolean;
  showServices?: boolean;
  showTestimonials?: boolean;
  googleAnalyticsId?: string;
  facebookPixelId?: string;
  twitterHandle?: string;
  footer?: {
    text?: string;
    copyrightText?: string;
    links?: Array<{
      title?: string;
      url?: string;
      _key: string;
    }>;
  };
  maintenanceMode?: boolean;
  maintenanceMessage?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  submittedAt?: string;
  status?: "new" | "archived";
  notes?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  features?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  deliverables?: Array<string>;
  pricing?: {
    startingPrice?: number;
    priceType?: "hourly" | "project" | "monthly" | "custom";
    description?: string;
  };
  timeline?: string;
  featured?: boolean;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?:
    | "tutorial"
    | "technical"
    | "ai-ml"
    | "web-dev"
    | "career"
    | "opinion"
    | "showcase"
    | "best-practices"
    | "news";
  tags?: Array<string>;
  publishedAt?: string;
  readTime?: number;
};

export type Achievement = {
  _id: string;
  _type: "achievement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?:
    | "award"
    | "hackathon"
    | "publication"
    | "speaking"
    | "open-source"
    | "milestone"
    | "recognition"
    | "other";
  issuer?: string;
  date?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  featured?: boolean;
  order?: number;
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  issuer?: string;
  issueDate?: string;
  expiryDate?: string;
  credentialId?: string;
  credentialUrl?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  position?: string;
  company?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  testimonial?: string;
  rating?: number;
  date?: string;
  linkedinUrl?: string;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  fieldOfStudy?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  gpa?: string;
  description?: string;
  achievements?: Array<string>;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  position?: string;
  employmentType?:
    | "full-time"
    | "part-time"
    | "contract"
    | "freelance"
    | "internship";
  location?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  responsibilities?: Array<string>;
  achievements?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  companyWebsite?: string;
  order?: number;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?:
    | "frontend"
    | "backend"
    | "ai-ml"
    | "devops"
    | "database"
    | "mobile"
    | "cloud"
    | "testing"
    | "design"
    | "tools"
    | "soft-skills"
    | "other";
  proficiency?: "beginner" | "intermediate" | "advanced" | "expert";
  percentage?: number;
  yearsOfExperience?: number;
  color?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tagline?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  category?:
    | "web-app"
    | "mobile-app"
    | "ai-ml"
    | "api-backend"
    | "devops"
    | "open-source"
    | "cli-tool"
    | "desktop-app"
    | "browser-extension"
    | "game"
    | "other";
  liveUrl?: string;
  githubUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  headline?: string;
  headlineStaticText?: string;
  headlineAnimatedWords?: Array<string>;
  headlineAnimationDuration?: number;
  shortBio?: string;
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  location?: string;
  availability?: "available" | "open" | "unavailable";
  socialLinks?: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  };
  yearsOfExperience?: number;
  stats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Navigation
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Contact
  | Service
  | Slug
  | Blog
  | Achievement
  | Certification
  | Testimonial
  | Education
  | Experience
  | Skill
  | Project
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./components/FloatingDock.tsx
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"] | order(order asc){  title,  href,  icon,  isExternal}
export type NAVIGATION_QUERYResult = Array<{
  title: string | null;
  href: string | null;
  icon: string | null;
  isExternal: boolean | null;
}>;

// Source: ./components/chat/ChatWrapper.tsx
// Variable: CHAT_PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{    _id,    _type,    _createdAt,    _updatedAt,    _rev,    firstName,    lastName,    headline,    shortBio,    email,    phone,    location,    availability,    socialLinks,    yearsOfExperience,    profileImage  }
export type CHAT_PROFILE_QUERYResult =
  | {
      _id: "singleton-profile";
      _type: "achievement";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "blog";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "certification";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "contact";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: string | null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "education";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "experience";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: string | null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "navigation";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "profile";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: string | null;
      lastName: string | null;
      headline: string | null;
      shortBio: string | null;
      email: string | null;
      phone: string | null;
      location: string | null;
      availability: "available" | "open" | "unavailable" | null;
      socialLinks: {
        github?: string;
        linkedin?: string;
        twitter?: string;
        website?: string;
        medium?: string;
        devto?: string;
        youtube?: string;
        stackoverflow?: string;
      } | null;
      yearsOfExperience: number | null;
      profileImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }
  | {
      _id: "singleton-profile";
      _type: "project";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "sanity.fileAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "service";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "siteSettings";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "skill";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: number | null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "testimonial";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | null;

// Source: ./components/sections/AboutSection.tsx
// Variable: ABOUT_QUERY
// Query: *[_id == "singleton-profile"][0]{  firstName,  lastName,  fullBio,  yearsOfExperience,  stats,  email,  phone,  location}
export type ABOUT_QUERYResult =
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      yearsOfExperience: null;
      stats: null;
      email: null;
      phone: null;
      location: null;
    }
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      yearsOfExperience: number | null;
      stats: null;
      email: null;
      phone: null;
      location: null;
    }
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      yearsOfExperience: null;
      stats: null;
      email: null;
      phone: null;
      location: string | null;
    }
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      yearsOfExperience: null;
      stats: null;
      email: string | null;
      phone: null;
      location: null;
    }
  | {
      firstName: string | null;
      lastName: string | null;
      fullBio: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      yearsOfExperience: number | null;
      stats: Array<{
        label?: string;
        value?: string;
        _key: string;
      }> | null;
      email: string | null;
      phone: string | null;
      location: string | null;
    }
  | null;

// Source: ./components/sections/AchievementsSection.tsx
// Variable: ACHIEVEMENTS_QUERY
// Query: *[_type == "achievement"] | order(date desc){  title,  type,  issuer,  date,  description,  image,  url,  featured,  order}
export type ACHIEVEMENTS_QUERYResult = Array<{
  title: string | null;
  type:
    | "award"
    | "hackathon"
    | "milestone"
    | "open-source"
    | "other"
    | "publication"
    | "recognition"
    | "speaking"
    | null;
  issuer: string | null;
  date: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url: string | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ./components/sections/BlogSection.tsx
// Variable: BLOG_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc){  title,  slug,  excerpt,  category,  tags,  publishedAt,  readTime,  featuredImage}
export type BLOG_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  category:
    | "ai-ml"
    | "best-practices"
    | "career"
    | "news"
    | "opinion"
    | "showcase"
    | "technical"
    | "tutorial"
    | "web-dev"
    | null;
  tags: Array<string> | null;
  publishedAt: string | null;
  readTime: number | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ./components/sections/CertificationsSection.tsx
// Variable: CERTIFICATIONS_QUERY
// Query: *[_type == "certification"] | order(issueDate desc){  name,  issuer,  issueDate,  expiryDate,  credentialId,  credentialUrl,  logo,  description,  skills[]->{name, category},  order}
export type CERTIFICATIONS_QUERYResult = Array<{
  name: string | null;
  issuer: string | null;
  issueDate: string | null;
  expiryDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  skills: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "mobile"
      | "other"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
  }> | null;
  order: number | null;
}>;

// Source: ./components/sections/ContactSection.tsx
// Variable: PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{  email,  phone,  location,  socialLinks}
export type PROFILE_QUERYResult =
  | {
      email: null;
      phone: null;
      location: null;
      socialLinks: null;
    }
  | {
      email: null;
      phone: null;
      location: string | null;
      socialLinks: null;
    }
  | {
      email: string | null;
      phone: null;
      location: null;
      socialLinks: null;
    }
  | {
      email: string | null;
      phone: string | null;
      location: string | null;
      socialLinks: {
        github?: string;
        linkedin?: string;
        twitter?: string;
        website?: string;
        medium?: string;
        devto?: string;
        youtube?: string;
        stackoverflow?: string;
      } | null;
    }
  | null;

// Source: ./components/sections/EducationSection.tsx
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(endDate desc, startDate desc){  institution,  degree,  fieldOfStudy,  startDate,  endDate,  current,  gpa,  description,  achievements,  logo,  website,  order}
export type EDUCATION_QUERYResult = Array<{
  institution: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  gpa: string | null;
  description: string | null;
  achievements: Array<string> | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  website: string | null;
  order: number | null;
}>;

// Source: ./components/sections/ExperienceSection.tsx
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(startDate desc){  company,  position,  employmentType,  location,  startDate,  endDate,  current,  description,  responsibilities,  achievements,  technologies[]->{name, category},  companyLogo,  companyWebsite}
export type EXPERIENCE_QUERYResult = Array<{
  company: string | null;
  position: string | null;
  employmentType:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | null;
  location: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  responsibilities: Array<string> | null;
  achievements: Array<string> | null;
  technologies: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "mobile"
      | "other"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
  }> | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyWebsite: string | null;
}>;

// Source: ./components/sections/HeroSection.tsx
// Variable: HERO_QUERY
// Query: *[_id == "singleton-profile"][0]{  firstName,  lastName,  headline,  headlineStaticText,  headlineAnimatedWords,  headlineAnimationDuration,  shortBio,  email,  phone,  location,  availability,  socialLinks,  yearsOfExperience,  profileImage}
export type HERO_QUERYResult =
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: number | null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: null;
      phone: null;
      location: string | null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: string | null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: string | null;
      lastName: string | null;
      headline: string | null;
      headlineStaticText: string | null;
      headlineAnimatedWords: Array<string> | null;
      headlineAnimationDuration: number | null;
      shortBio: string | null;
      email: string | null;
      phone: string | null;
      location: string | null;
      availability: "available" | "open" | "unavailable" | null;
      socialLinks: {
        github?: string;
        linkedin?: string;
        twitter?: string;
        website?: string;
        medium?: string;
        devto?: string;
        youtube?: string;
        stackoverflow?: string;
      } | null;
      yearsOfExperience: number | null;
      profileImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }
  | null;

// Source: ./components/sections/ProjectsSection.tsx
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(order asc)[0...6]{  title,  slug,  tagline,  category,  liveUrl,  githubUrl,  coverImage,  technologies[]->{name, category, color}}
export type PROJECTS_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  tagline: string | null;
  category:
    | "ai-ml"
    | "api-backend"
    | "browser-extension"
    | "cli-tool"
    | "desktop-app"
    | "devops"
    | "game"
    | "mobile-app"
    | "open-source"
    | "other"
    | "web-app"
    | null;
  liveUrl: string | null;
  githubUrl: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  technologies: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "mobile"
      | "other"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
    color: string | null;
  }> | null;
}>;

// Source: ./components/sections/ServicesSection.tsx
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc, _createdAt desc){  title,  slug,  icon,  shortDescription,  fullDescription,  features,  technologies[]->{name, category},  deliverables,  pricing,  timeline,  featured,  order}
export type SERVICES_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  icon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortDescription: string | null;
  fullDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  features: Array<string> | null;
  technologies: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "mobile"
      | "other"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
  }> | null;
  deliverables: Array<string> | null;
  pricing: {
    startingPrice?: number;
    priceType?: "custom" | "hourly" | "monthly" | "project";
    description?: string;
  } | null;
  timeline: string | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ./components/sections/SkillsSection.tsx
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, order asc){  name,  category,  proficiency,  percentage,  yearsOfExperience,  color}
export type SKILLS_QUERYResult = Array<{
  name: string | null;
  category:
    | "ai-ml"
    | "backend"
    | "cloud"
    | "database"
    | "design"
    | "devops"
    | "frontend"
    | "mobile"
    | "other"
    | "soft-skills"
    | "testing"
    | "tools"
    | null;
  proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
  percentage: number | null;
  yearsOfExperience: number | null;
  color: string | null;
}>;

// Source: ./components/sections/TestimonialsSection.tsx
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true] | order(order asc){  name,  position,  company,  testimonial,  rating,  date,  avatar,  companyLogo,  linkedinUrl}
export type TESTIMONIALS_QUERYResult = Array<{
  name: string | null;
  position: string | null;
  company: string | null;
  testimonial: string | null;
  rating: number | null;
  date: string | null;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  linkedinUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "navigation"] | order(order asc){\n  title,\n  href,\n  icon,\n  isExternal\n}': NAVIGATION_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    firstName,\n    lastName,\n    headline,\n    shortBio,\n    email,\n    phone,\n    location,\n    availability,\n    socialLinks,\n    yearsOfExperience,\n    profileImage\n  }': CHAT_PROFILE_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n  firstName,\n  lastName,\n  fullBio,\n  yearsOfExperience,\n  stats,\n  email,\n  phone,\n  location\n}': ABOUT_QUERYResult;
    '*[_type == "achievement"] | order(date desc){\n  title,\n  type,\n  issuer,\n  date,\n  description,\n  image,\n  url,\n  featured,\n  order\n}': ACHIEVEMENTS_QUERYResult;
    '*[_type == "blog"] | order(publishedAt desc){\n  title,\n  slug,\n  excerpt,\n  category,\n  tags,\n  publishedAt,\n  readTime,\n  featuredImage\n}': BLOG_QUERYResult;
    '*[_type == "certification"] | order(issueDate desc){\n  name,\n  issuer,\n  issueDate,\n  expiryDate,\n  credentialId,\n  credentialUrl,\n  logo,\n  description,\n  skills[]->{name, category},\n  order\n}': CERTIFICATIONS_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n  email,\n  phone,\n  location,\n  socialLinks\n}': PROFILE_QUERYResult;
    '*[_type == "education"] | order(endDate desc, startDate desc){\n  institution,\n  degree,\n  fieldOfStudy,\n  startDate,\n  endDate,\n  current,\n  gpa,\n  description,\n  achievements,\n  logo,\n  website,\n  order\n}': EDUCATION_QUERYResult;
    '*[_type == "experience"] | order(startDate desc){\n  company,\n  position,\n  employmentType,\n  location,\n  startDate,\n  endDate,\n  current,\n  description,\n  responsibilities,\n  achievements,\n  technologies[]->{name, category},\n  companyLogo,\n  companyWebsite\n}': EXPERIENCE_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n  firstName,\n  lastName,\n  headline,\n  headlineStaticText,\n  headlineAnimatedWords,\n  headlineAnimationDuration,\n  shortBio,\n  email,\n  phone,\n  location,\n  availability,\n  socialLinks,\n  yearsOfExperience,\n  profileImage\n}': HERO_QUERYResult;
    '*[_type == "project" && featured == true] | order(order asc)[0...6]{\n  title,\n  slug,\n  tagline,\n  category,\n  liveUrl,\n  githubUrl,\n  coverImage,\n  technologies[]->{name, category, color}\n}': PROJECTS_QUERYResult;
    '*[_type == "service"] | order(order asc, _createdAt desc){\n  title,\n  slug,\n  icon,\n  shortDescription,\n  fullDescription,\n  features,\n  technologies[]->{name, category},\n  deliverables,\n  pricing,\n  timeline,\n  featured,\n  order\n}': SERVICES_QUERYResult;
    '*[_type == "skill"] | order(category asc, order asc){\n  name,\n  category,\n  proficiency,\n  percentage,\n  yearsOfExperience,\n  color\n}': SKILLS_QUERYResult;
    '*[_type == "testimonial" && featured == true] | order(order asc){\n  name,\n  position,\n  company,\n  testimonial,\n  rating,\n  date,\n  avatar,\n  companyLogo,\n  linkedinUrl\n}': TESTIMONIALS_QUERYResult;
  }
}
